#!/usr/bin/env bash
# ============================================================================
# Bulwark — initial setup
# Run this on a fresh VPS to configure it as the management bridge node.
# After setup, use the Telegram bot to add exit nodes.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------
if [[ "$(uname)" != "Linux" ]]; then
    echo "ERROR: Bulwark requires Linux. Exiting."
    exit 1
fi

if [[ "$(id -u)" -ne 0 ]]; then
    echo "ERROR: Run as root: sudo ./setup.sh"
    exit 1
fi

echo "============================================"
echo "  Bulwark — Infrastructure Manager"
echo "============================================"
echo ""

# ---------------------------------------------------------------------------
# Gather input
# ---------------------------------------------------------------------------
read -rp "Telegram Bot Token (from @BotFather): " TG_TOKEN
if [[ -z "${TG_TOKEN}" ]]; then
    echo "ERROR: Bot token is required."
    exit 1
fi

read -rp "Telegram Chat ID (your chat with the bot): " TG_CHAT_ID
if [[ -z "${TG_CHAT_ID}" ]]; then
    echo "ERROR: Chat ID is required."
    exit 1
fi

read -rp "Your Telegram User ID (for admin access): " TG_ADMIN_ID
if [[ -z "${TG_ADMIN_ID}" ]]; then
    echo "ERROR: Admin user ID is required."
    exit 1
fi

# Auto-detect server IP
echo ""
echo "Detecting server IP..."
SERVER_IP=$(curl -s --max-time 10 ifconfig.me 2>/dev/null || \
            curl -s --max-time 10 icanhazip.com 2>/dev/null || \
            ip route get 1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}' || \
            echo "")

if [[ -z "${SERVER_IP}" ]]; then
    read -rp "Could not detect IP. Enter server IP manually: " SERVER_IP
fi
echo "Server IP: ${SERVER_IP}"

read -rp "Node name [management]: " NODE_NAME
NODE_NAME="${NODE_NAME:-management}"

read -rp "Region code (ru, fi, at, de, nl, us) [ru]: " REGION
REGION="${REGION:-ru}"

echo ""
read -rsp "SSH password for this server (for bot self-management): " SSH_PASSWORD
echo ""
echo ""
read -rp "Reality SNI domain (must be reachable from this server, e.g. google.com): " REALITY_SNI
REALITY_SNI="${REALITY_SNI:-google.com}"

NODE_NAME_UPPER=$(echo "${NODE_NAME}" | tr '[:lower:]' '[:upper:]')
SSH_ENV_VAR="${NODE_NAME_UPPER}_SSH_PASSWORD"

# ---------------------------------------------------------------------------
# Generate random API prefixes
# ---------------------------------------------------------------------------
SUB_PREFIX="/$(head -c 12 /dev/urandom | base64 | tr -dc 'a-z0-9' | head -c 8)"
AWG_PREFIX="/$(head -c 12 /dev/urandom | base64 | tr -dc 'a-z0-9' | head -c 8)"
SUB_UUID="$(cat /proc/sys/kernel/random/uuid)"
BR_BASE=$(( RANDOM % 10000 + 20000 ))

# ---------------------------------------------------------------------------
# Generate .env
# ---------------------------------------------------------------------------
echo ""
echo "[bulwark] Generating .env..."
cat > "${SCRIPT_DIR}/.env" <<EOF
# Bulwark — generated by setup.sh
TELEGRAM_BOT_TOKEN=${TG_TOKEN}
TELEGRAM_CHAT_ID=${TG_CHAT_ID}
${SSH_ENV_VAR}=${SSH_PASSWORD}
SUBSCRIPTION_UUID=${SUB_UUID}
PORTAL_SUB_PREFIX=${SUB_PREFIX}
PORTAL_AWG_PREFIX=${AWG_PREFIX}
EOF
chmod 600 "${SCRIPT_DIR}/.env"

# ---------------------------------------------------------------------------
# Generate config/nodes.yaml
# ---------------------------------------------------------------------------
echo "[bulwark] Generating config/nodes.yaml..."
cat > "${SCRIPT_DIR}/config/nodes.yaml" <<EOF
---
nodes:
  ${NODE_NAME}:
    name: "${NODE_NAME}"
    display_name: "Management Bridge"
    ip: "${SERVER_IP}"
    ssh_port: 22
    ssh_user: root
    ssh_key_path: ""
    ssh_password_env: "${SSH_ENV_VAR}"
    role: bridge
    region: "${REGION}"
    priority: 1
    enabled: true
    protocols: []
    inbound_port_start: ${BR_BASE}
    description: "Management bridge node."
EOF

# ---------------------------------------------------------------------------
# Generate config/global.yaml
# ---------------------------------------------------------------------------
echo "[bulwark] Generating config/global.yaml..."
if [[ -f "${SCRIPT_DIR}/config/global.yaml.example" ]]; then
    cp "${SCRIPT_DIR}/config/global.yaml.example" "${SCRIPT_DIR}/config/global.yaml"
    GY="${SCRIPT_DIR}/config/global.yaml"

    # Admin ID
    sed -i "s/admin_user_ids: \[\]/admin_user_ids: [${TG_ADMIN_ID}]/" "${GY}"

    # Randomize AWG obfuscation parameters (unique per installation)
    AWG_JC=$(( RANDOM % 6 + 3 ))           # 3-8
    AWG_JMIN=$(( RANDOM % 30 + 30 ))       # 30-59
    AWG_JMAX=$(( RANDOM % 40 + 60 ))       # 60-99
    AWG_S3=$(( RANDOM % 48 + 16 ))         # 16-63
    AWG_S4=$(( RANDOM % 24 + 8 ))          # 8-31
    AWG_HRANGE=$(( RANDOM * RANDOM % 900000 + 100000 ))    # 100K-1M
    AWG_H4RANGE=$(( RANDOM * RANDOM % 90000000 + 10000000 )) # 10M-100M

    # Generate random CPS-format signature packets
    SIG1=$(printf '0x%08x' $(( RANDOM * RANDOM )))
    SIG2=$(printf '0x%08x' $(( RANDOM * RANDOM )))
    RC1=$(( RANDOM % 16 + 4 ))
    RC2=$(( RANDOM % 24 + 8 ))
    R1=$(( RANDOM % 60 + 40 ))
    R2=$(( RANDOM % 60 + 40 ))
    AWG_I1="<b ${SIG1}01><rc ${RC1}><t><r ${R1}>"
    AWG_I2="<b ${SIG2}fa><t><rc ${RC2}><r ${R2}>"

    sed -i "s/^  jc: 0/  jc: ${AWG_JC}/" "${GY}"
    sed -i "s/^  jmin: 0/  jmin: ${AWG_JMIN}/" "${GY}"
    sed -i "s/^  jmax: 0/  jmax: ${AWG_JMAX}/" "${GY}"
    sed -i "s/^  s3_default: 0/  s3_default: ${AWG_S3}/" "${GY}"
    sed -i "s/^  s4_default: 0/  s4_default: ${AWG_S4}/" "${GY}"
    sed -i "s/^  h_range_default: 0/  h_range_default: ${AWG_HRANGE}/" "${GY}"
    sed -i "s/^  h4_range_default: 0/  h4_range_default: ${AWG_H4RANGE}/" "${GY}"
    sed -i "s|^  i1: \"\"|  i1: \"${AWG_I1}\"|" "${GY}"
    sed -i "s|^  i2: \"\"|  i2: \"${AWG_I2}\"|" "${GY}"

    # Pick random masquerade site for Hysteria2
    MASQ_SITES=("https://www.google.com/" "https://www.amazon.com/" "https://www.microsoft.com/" "https://www.apple.com/" "https://www.wikipedia.org/" "https://www.github.com/" "https://www.cloudflare.com/")
    MASQ_URL="${MASQ_SITES[$((RANDOM % ${#MASQ_SITES[@]}))]}"
    sed -i "s|masquerade_url: \"\"|masquerade_url: \"${MASQ_URL}\"|" "${GY}"

    # Bridge relay ports (BR_BASE generated above, shared with nodes.yaml)
    BR_AWG=$(( BR_BASE + 10 ))
    BR_AWG_SINGLE=$(( BR_BASE + 20 ))
    sed -i "s/^  inbound_port_start: 0/  inbound_port_start: ${BR_BASE}/" "${GY}"
    sed -i "s/^  awg_relay_port_start: 0/  awg_relay_port_start: ${BR_AWG}/" "${GY}"
    sed -i "s/^  awg_relay_port_start_single: 0/  awg_relay_port_start_single: ${BR_AWG_SINGLE}/" "${GY}"

    echo "[bulwark] Config randomized (bridge ports: ${BR_BASE}+)"
else
    echo "WARNING: config/global.yaml.example not found. Copy manually."
fi

# ---------------------------------------------------------------------------
# Initialize empty runtime files
# ---------------------------------------------------------------------------
mkdir -p "${SCRIPT_DIR}/config/secrets"
touch "${SCRIPT_DIR}/config/secrets/.gitkeep"

# ---------------------------------------------------------------------------
# Install Python dependencies
# ---------------------------------------------------------------------------
echo "[bulwark] Installing system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq python3 python3-pip python3-venv curl wget git unzip jq

echo "[bulwark] Creating virtualenv..."
python3 -m venv "${SCRIPT_DIR}/venv"
"${SCRIPT_DIR}/venv/bin/pip" install --quiet --upgrade pip
"${SCRIPT_DIR}/venv/bin/pip" install --quiet -r "${SCRIPT_DIR}/requirements.txt"

PYTHON="${SCRIPT_DIR}/venv/bin/python"

# ---------------------------------------------------------------------------
# Base system preparation (firewall, sysctl, directories)
# ---------------------------------------------------------------------------
echo "[bulwark] Running base system preparation..."
bash "${SCRIPT_DIR}/deploy/scripts/install_base.sh"

# ---------------------------------------------------------------------------
# Install xray binary (needed for bridge relay)
# ---------------------------------------------------------------------------
echo "[bulwark] Installing xray-core (for bridge relay)..."
bash "${SCRIPT_DIR}/deploy/scripts/install_xray.sh"

# ---------------------------------------------------------------------------
# Generate secrets for management bridge
# ---------------------------------------------------------------------------
echo "[bulwark] Generating secrets for ${NODE_NAME}..."
"${PYTHON}" "${SCRIPT_DIR}/cli.py" secrets regenerate "${NODE_NAME}" 2>/dev/null || \
    echo "WARNING: Could not generate secrets. Run manually: python cli.py secrets regenerate ${NODE_NAME}"

# Write Reality SNI into generated secrets
SECRETS_FILE="${SCRIPT_DIR}/config/secrets/${NODE_NAME}.yaml"
if [[ -f "${SECRETS_FILE}" ]]; then
    sed -i "s|^reality_dest:.*|reality_dest: \"${REALITY_SNI}:443\"|" "${SECRETS_FILE}"
    sed -i "s|^reality_server_name:.*|reality_server_name: \"${REALITY_SNI}\"|" "${SECRETS_FILE}"
    echo "[bulwark] Reality SNI set to: ${REALITY_SNI}"
fi

# ---------------------------------------------------------------------------
# Install systemd service
# ---------------------------------------------------------------------------
echo "[bulwark] Installing systemd service..."

SYSTEMD_UNIT="/etc/systemd/system/bulwark-bot.service"
cat > "${SYSTEMD_UNIT}" <<EOF
[Unit]
Description=Bulwark Bot + Monitor
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=${SCRIPT_DIR}
EnvironmentFile=${SCRIPT_DIR}/.env
Environment=PYTHONUNBUFFERED=1
ExecStart=${PYTHON} ${SCRIPT_DIR}/cli.py bot start
Restart=on-failure
RestartSec=15
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable bulwark-bot

# ---------------------------------------------------------------------------
# Install portal (subscription API)
# ---------------------------------------------------------------------------
echo "[bulwark] Setting up portal..."
PORTAL_DIR="${SCRIPT_DIR}/deploy/portal"
RUNTIME_DIR="${PORTAL_DIR}/runtime"
mkdir -p "${RUNTIME_DIR}"

# Write subscription token for portal
echo "${SUB_UUID}" > "${PORTAL_DIR}/subscription_token.txt"

PORTAL_UNIT="/etc/systemd/system/bulwark-portal.service"
cat > "${PORTAL_UNIT}" <<EOF
[Unit]
Description=Bulwark Portal API
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=${SCRIPT_DIR}
EnvironmentFile=${SCRIPT_DIR}/.env
Environment=PYTHONUNBUFFERED=1
ExecStart=${SCRIPT_DIR}/venv/bin/gunicorn --bind 127.0.0.1:8787 --workers 2 --chdir ${PORTAL_DIR} app:app
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable bulwark-portal

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================"
echo "  Bulwark setup complete!"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. Start the bot:  systemctl start bulwark-bot"
echo "  2. Open Telegram and send /start to your bot"
echo "  3. Use the bot to add exit nodes (wizard)"
echo ""
echo "Useful commands:"
echo "  journalctl -u bulwark-bot -f     — view bot logs"
echo "  systemctl restart bulwark-bot     — restart bot"
echo "  ${PYTHON} ${SCRIPT_DIR}/cli.py status  — check node status"
echo ""
