"""
Bulwark Subscription API — lightweight Flask service.

API paths are randomised at setup time.
Configured via environment variables PORTAL_SUB_PREFIX and PORTAL_AWG_PREFIX,
falling back to /sub and /awg-api if not set.
"""

import json
import os
import subprocess
import base64
import uuid

from flask import Flask, jsonify, request, Response

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SUB_TOKEN_FILE = os.path.join(BASE_DIR, "subscription_token.txt")
DOMAIN = os.environ.get("PORTAL_DOMAIN", "localhost")

# Random prefixes generated by setup.sh — makes API paths unpredictable
SUB_PREFIX = os.environ.get("PORTAL_SUB_PREFIX", "/sub")
AWG_PREFIX = os.environ.get("PORTAL_AWG_PREFIX", "/awg-api")

RUNTIME_DIR = os.path.join(BASE_DIR, "runtime")
OVERRIDE_SUB_FILE = os.path.join(RUNTIME_DIR, "subscription.b64")
AWG_USERS_FILE = os.path.join(RUNTIME_DIR, "awg_users.json")

# Bulwark project root (auto-detected: two levels up from deploy/portal/app.py)
BW_DIR = os.environ.get("BW_DIR", os.path.dirname(os.path.dirname(BASE_DIR)))
BW_CLI = os.path.join(BW_DIR, "venv/bin/python")
BW_SCRIPT = os.path.join(BW_DIR, "cli.py")

app = Flask(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def read_subscription_token() -> str:
    try:
        with open(SUB_TOKEN_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    except FileNotFoundError:
        return ""


def generate_subscription_content() -> str:
    """Return base64 subscription from runtime override file."""
    if os.path.exists(OVERRIDE_SUB_FILE):
        with open(OVERRIDE_SUB_FILE, "r", encoding="utf-8") as _f:
            return _f.read().strip()
    return ""


# ---------------------------------------------------------------------------
# AWG API helpers
# ---------------------------------------------------------------------------

def _load_awg_users() -> dict:
    """Load AWG API users. Checks both runtime/ and Bulwark config/ paths."""
    for path in [AWG_USERS_FILE, os.path.join(BW_DIR, "config", "awg_users.json")]:
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
    return {"users": {}}


def _lookup_user_by_api_key(api_key: str) -> dict | None:
    data = _load_awg_users()
    for user in data.get("users", {}).values():
        if user.get("api_key") == api_key and user.get("active", True):
            return user
    return None


def _find_existing_peer(user: dict, client_pubkey: str) -> dict | None:
    """Check if this pubkey is already provisioned for this user."""
    for peer in user.get("peers", []):
        if peer.get("pubkey") == client_pubkey:
            return peer
    return None


def _select_exit_node(user: dict, requested_node: str = "") -> str:
    """Pick the best available exit node for the user.

    Priority:
    1. requested_node (if in user's list)
    2. First assigned node not in node_overrides disabled list
    3. First assigned node (fallback)
    """
    nodes = user.get("assigned_nodes", [])
    if not nodes:
        return ""

    if requested_node and requested_node in nodes:
        return requested_node

    overrides_path = os.path.join(BW_DIR, "config", "node_overrides.json")
    disabled = set()
    try:
        if os.path.exists(overrides_path):
            with open(overrides_path, "r") as f:
                disabled = set(json.load(f).get("disabled", []))
    except Exception:
        pass

    for n in nodes:
        if n not in disabled:
            return n

    return nodes[0]


def _provision_peer_via_cli(node_name: str, client_pubkey: str) -> dict | None:
    """Create a new AWG peer on a node using the Bulwark CLI."""
    try:
        result = subprocess.run(
            [BW_CLI, BW_SCRIPT, "awg", "add-peer", node_name,
             "--name", f"api-{uuid.uuid4().hex[:8]}",
             "--pubkey", client_pubkey],
            capture_output=True, text=True, timeout=60,
            cwd=BW_DIR,
        )
        if result.returncode != 0:
            app.logger.error("AWG provision failed: %s", result.stderr)
            return None
        for line in result.stdout.split("\n"):
            if "Address:" in line:
                addr = line.split("Address:")[-1].strip().rstrip("/32")
                return {"address": addr, "pubkey": client_pubkey, "node": node_name}
        return {"address": "unknown", "pubkey": client_pubkey, "node": node_name}
    except Exception as e:
        app.logger.error("AWG provision error: %s", e)
        return None


def _generate_type1_config(node_name: str, client_pubkey: str) -> str | None:
    """Generate a Type 1 vpn:// config for a peer via Bulwark CLI."""
    try:
        result = subprocess.run(
            [BW_CLI, BW_SCRIPT, "awg", "gen-link", node_name,
             "--pubkey", client_pubkey],
            capture_output=True, text=True, timeout=30,
            cwd=BW_DIR,
        )
        if result.returncode == 0:
            for line in result.stdout.strip().split("\n"):
                if line.startswith("vpn://"):
                    return line.strip()
        app.logger.error("gen-link failed: %s", result.stderr)
        return None
    except Exception as e:
        app.logger.error("gen-link error: %s", e)
        return None


# ---------------------------------------------------------------------------
# Routes — Subscriptions
# ---------------------------------------------------------------------------

@app.route(f"{SUB_PREFIX}/<token>")
def subscription(token: str):
    """V2Ray subscription endpoint — returns base64-encoded VLESS+HY2 URLs."""
    expected_token = read_subscription_token()
    if not expected_token or token != expected_token:
        return Response("Invalid subscription token", status=404, mimetype="text/plain")

    try:
        content = generate_subscription_content()
        if not content:
            return Response("No subscription data", status=404, mimetype="text/plain")
        return Response(content, status=200, mimetype="text/plain")
    except Exception as e:
        return Response(f"Error: {e}", status=500, mimetype="text/plain")



# ---------------------------------------------------------------------------
# Routes — AWG API (Type 2 vpn:// auto-provisioning)
# ---------------------------------------------------------------------------

@app.route(f"{AWG_PREFIX}/", methods=["POST"])
@app.route(f"{AWG_PREFIX}/<requested_node>/", methods=["POST"])
def api_request_awg(requested_node: str = ""):
    """AWG API Subscription endpoint.

    AmneziaVPN client sends POST with pubkey, server returns full config.
    Auth: Api-Key header.
    """
    # 1. Auth
    auth_header = request.headers.get("Authorization", "")
    api_key = auth_header.replace("Api-Key ", "").strip()
    if not api_key:
        return jsonify({"error": "missing api_key"}), 401

    user = _lookup_user_by_api_key(api_key)
    if not user:
        return jsonify({"error": "unauthorized"}), 401

    # 2. Parse request
    data = request.get_json(silent=True) or {}
    client_pubkey = data.get("public_key", "").strip()

    if not client_pubkey:
        return jsonify({"error": "missing public_key"}), 400

    # 3. Find existing peer or provision new one
    existing = _find_existing_peer(user, client_pubkey)
    if existing:
        node_name = existing["node"]
    else:
        if len(user.get("peers", [])) >= user.get("max_peers", 5):
            return jsonify({"error": "max_peers limit reached"}), 403

        node_name = _select_exit_node(user, requested_node)
        if not node_name:
            return jsonify({"error": "no assigned nodes"}), 500

        new_peer = _provision_peer_via_cli(node_name, client_pubkey)
        if not new_peer:
            return jsonify({"error": "peer provisioning failed"}), 500

        existing = new_peer

    # 4. Generate config
    vpn_link = _generate_type1_config(node_name, client_pubkey)
    if not vpn_link:
        return jsonify({"error": "config generation failed"}), 500

    return jsonify({"config": vpn_link})


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8787, debug=False)
